
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sliot_dev
    ports:
      - "55432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

  n8n-postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8n
      POSTGRES_DB: n8n_db
    ports:
      - "55433:5432"
    volumes:
      - n8n_postgres_data:/var/lib/postgresql/data

  n8n:
    image: n8nio/n8n:latest
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: n8n-postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8n_db
      DB_POSTGRESDB_USER: n8n
      DB_POSTGRESDB_PASSWORD: n8n
    ports:
      - "5678:5678"
    depends_on:
      - n8n-postgres

  frontend:
    build: ./frontend
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/sliot_dev
      NODE_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data_dev:
  n8n_postgres_data:
