name: Deploy to EC2 (Docker Hub)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Frontend image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/sliot-nextjs:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and push CMS image
      uses: docker/build-push-action@v5
      with:
        context: ./cms
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/sliot-cms:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Deploy to EC2
      if: github.ref == 'refs/heads/main'
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Login to Docker Hub
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          
          # Navigate to project directory
          cd /home/ubuntu/sliot-project
          
          # Pull latest code
          git pull origin main
          
          # Pull latest images
          docker compose -f docker-compose.yml -f docker-compose.prod.yml pull
          
          # Restart services with new images
          docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --force-recreate
          
          # Clean up old images
          docker image prune -f
          
          # Show status
          docker compose ps